<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                </strong>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>

                        <?php if ($block->isGlsPolandParcelShopShipping($_order)): ?>
                            <?php
                            $parcelShopId = $_order->getData('gls_poland_parcel_shop_id');
                            if ($parcelShopId):
                                $parcelShopName1 = $_order->getData('gls_poland_parcel_shop_name1');
                                $parcelShopName2 = $_order->getData('gls_poland_parcel_shop_name2');
                                $parcelShopName3 = $_order->getData('gls_poland_parcel_shop_name3');
                                $parcelShopCountry = $_order->getData('gls_poland_parcel_shop_country');
                                $parcelShopZipcode = $_order->getData('gls_poland_parcel_shop_zipcode');
                                $parcelShopCity = $_order->getData('gls_poland_parcel_shop_city');
                                $parcelShopStreet = $_order->getData('gls_poland_parcel_shop_street');
                                ?>
                                <div class="admin__page-section-item-content">
                                    <br/>
                                    <strong>
                                        <?= $block->escapeHtml(__('GLS Poland Parcel Shop')) ?>
                                    </strong>
                                    <br/>
                                    <strong>
                                        <?= $block->escapeHtml(__('ID: ')) ?>
                                    </strong><?= $block->escapeHtml($parcelShopId) ?>
                                    <?php
                                    if ($parcelShopName1 !== null && $parcelShopName1 !== $parcelShopId):  ?>
                                        <br/><?= $block->escapeHtml($parcelShopName1) ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($parcelShopName2 !== null && $parcelShopName2 !== $parcelShopId):  ?>
                                        <br/><?= $block->escapeHtml($parcelShopName2) ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($parcelShopName3 !== null && $parcelShopName3 !== $parcelShopId):  ?>
                                        <br/><?= $block->escapeHtml($parcelShopName3) ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($parcelShopStreet !== null):  ?>
                                        <br/><?= $block->escapeHtml($parcelShopStreet) ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($parcelShopZipcode !== null):  ?>
                                        <br/><?= $block->escapeHtml($parcelShopZipcode) ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($parcelShopCity !== null):  ?>
                                        <?= $block->escapeHtml(' ' . $parcelShopCity) ?>
                                    <?php endif; ?>
                                    <?php
                                    if ($parcelShopCountry !== null):  ?>
                                        <br/>
                                        <?= $block->escapeHtml(
                                            ' ' . $block->getCountryName($parcelShopCountry)
                                        ) ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?= $block->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
            </strong>
            <div class="box-content">
                <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
